# apps/otel/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OpenTelemetry is deployed via Helm, so no direct resources
  # This file exists for potential future customizations

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: homelab-gitops
      environment: homelab
      component: telemetry-collector
