# Configure OpenTelemetry Collector to send data to your existing stack
opentelemetry-collector:
  config:
    exporters:
      # Send traces to your Tempo instance
      otlp/tempo:
        endpoint: http://tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      
      # FIXED: Send ALL telemetry to your main collector
      otlp/main-collector:
        endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      
      # Keep debug for troubleshooting
      debug:
        verbosity: normal
        
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [spanmetrics, otlp/tempo, otlp/main-collector, debug]
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlp/main-collector, debug]  # Send metrics to your collector
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlp/main-collector, debug]  # Send logs to your collector
