# apps/otel/values.yaml - UPDATED TO USE HTTP ENDPOINT
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.131.0"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024

  exporters:
    debug:
      verbosity: detailed
    
    otlp/tempo:
      endpoint: http://tempo.monitoring.svc.cluster.local:4318  # CHANGED: Use HTTP port 4318
      tls:
        insecure: true
      headers: {}  # ADD: Explicit headers for HTTP

  service:
    telemetry:
      logs:
        level: debug  # Enable debug logging
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug, otlp/tempo]
