# apps/otel/values.yaml - FIXED FOR METRICS
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.131.0"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024

  exporters:
    debug:
      verbosity: detailed
    
    # Traces to Tempo
    otlp/tempo:
      endpoint: http://tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true
    
    # ADDED: Metrics to Prometheus
    prometheusremotewrite:
      endpoint: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
      remote_write_queue:
        enabled: true
        queue_size: 10000
        num_consumers: 5

  service:
    telemetry:
      logs:
        level: debug
    pipelines:
      # Traces pipeline (existing)
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug, otlp/tempo]
      
      # ADDED: Metrics pipeline
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug, prometheusremotewrite]
