# FILE: apps/argocd/projects/monitoring-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for the homelab monitoring stack
  sourceRepos:
    - '*'
  destinations:
    # REMOVED the 'argocd' namespace. 
    # The project should ONLY be allowed to deploy to the 'monitoring' namespace.
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
