apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CORRECTED: Pointing to your new GitOps repo
    repoURL: 'https://github.com/milenika/homelab-gitopps.git'
    targetRevision: HEAD
    path: 06_argocd_install 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
