apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CORRECTED: Pointing to your new GitOps repo
    repoURL: 'https://github.com/milenika/homelab-gitopps.git'
    targetRevision: HEAD
    # CORRECTED: Pointing to the new manifest directory
    path: 08_k8s_manifests 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
