apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/tracking-id: root:argoproj.io/Application:argocd/monitoring
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"2","argocd.argoproj.io/tracking-id":"root:argoproj.io/Application:argocd/monitoring"},"labels":{"app.kubernetes.io/managed-by":"argocd","app.kubernetes.io/part-of":"homelab-gitops"},"name":"monitoring","namespace":"argocd"},"spec":{"destination":{"namespace":"monitoring","server":"https://kubernetes.default.svc"},"ignoreDifferences":[{"group":"apps","jsonPointers":["/spec/replicas"],"kind":"Deployment"},{"group":"","jsonPointers":["/spec/clusterIP"],"kind":"Service"}],"project":"default","source":{"kustomize":{"buildOptions":"--enable-helm"},"path":"apps/monitoring/homelab","repoURL":"https://github.com/mikha-22/homelab-gitops","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":2,"maxDuration":"3m"},"limit":5},"syncOptions":["CreateNamespace=true","ServerSideApply=true","RespectIgnoreDifferences=true"]}}}
  creationTimestamp: "2025-07-07T02:02:08Z"
  generation: 4
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: homelab-gitops
  name: monitoring
  namespace: argocd
  resourceVersion: "28024"
  uid: d8b57db5-5016-485e-a65b-8bc923cf0d90
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
  - group: ""
    jsonPointers:
    - /spec/clusterIP
    kind: Service
  project: default
  source:
    path: apps/monitoring/homelab
    repoURL: https://github.com/mikha-22/homelab-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
status:
  conditions:
  - lastTransitionTime: "2025-07-07T02:02:08Z"
    message: |-
      Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `kustomize build <path to cached source>/apps/monitoring/homelab` failed exit status 1: Error: trouble configuring builtin HelmChartInflationGenerator with config: `
      includeCRDs: true
      name: kube-prometheus-stack
      namespace: monitoring
      releaseName: kube-prometheus-stack
      repo: https://prometheus-community.github.io/helm-charts
      valuesFile: kube-prometheus-stack-values.yaml
      version: 58.1.0
      `: must specify --enable-helm
    type: ComparisonError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-07-07T02:02:08Z"
    status: Healthy
  reconciledAt: "2025-07-07T02:02:14Z"
  resourceHealthSource: appTree
  sync:
    comparedTo:
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: apps
        jsonPointers:
        - /spec/replicas
        kind: Deployment
      - jsonPointers:
        - /spec/clusterIP
        kind: Service
      source:
        path: apps/monitoring/homelab
        repoURL: https://github.com/mikha-22/homelab-gitops
        targetRevision: HEAD
    status: Unknown
