apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps
spec:
  project: default
  source:
    repoURL: https://github.com/mikha-22/homelab-gitops
    targetRevision: HEAD
    path: apps/external-secrets
    
  destination:
    server: https://kubernetes.default.svc
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  # ADD THIS: Ignore differences in ExternalSecret metadata that ESO auto-adds
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/data/1/remoteRef/conversionStrategy
        - /spec/data/1/remoteRef/decodingStrategy
        - /spec/data/1/remoteRef/metadataPolicy
        - /spec/data/2/remoteRef/conversionStrategy
        - /spec/data/2/remoteRef/decodingStrategy
        - /spec/data/2/remoteRef/metadataPolicy
    # Use JQ expressions for more flexible matching
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - '.spec.data[]?.remoteRef.conversionStrategy'
        - '.spec.data[]?.remoteRef.decodingStrategy'
        - '.spec.data[]?.remoteRef.metadataPolicy'
