apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://djjudas21.github.io/charts/
    targetRevision: 8.2.4
    chart: homer
    helm:
      releaseName: homer
      values: |
        env:
          TZ: "Asia/Jakarta"

        service:
          main:
            ports:
              http:
                port: 8080

        ingress:
          main:
            enabled: true
            annotations:
              "kubernetes.io/ingress.class": "traefik"
              "external-dns.alpha.kubernetes.io/target": "52e6c172-8b5e-4167-b68f-20dd50299c3c.cfargotunnel.com"
              "external-dns.alpha.kubernetes.io/cloudflare-proxied": "true"
            hosts:
              - host: homer.milenika.dev
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: homer-tls
                hosts:
                  - homer.milenika.dev

        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          runAsGroup: 1000

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        persistence:
          config:
            enabled: true
            type: pvc
            storageClass: local-path
            accessMode: ReadWriteOnce
            size: 1Gi
            mountPath: /www/assets

        configmap:
          config:
            enabled: true
            data:
              config.yml: |
                ---
                title: "Mikha's Homelab"
                subtitle: "LGTM Stack & Services"
                logo: "logo.png"
                
                header: true
                                
                theme: default
                colors:
                  light:
                    highlight-primary: "#3367d6"
                    highlight-secondary: "#4285f4"
                    highlight-hover: "#5a95f5"
                    background: "#f5f5f5"
                    card-background: "#ffffff"
                    text: "#363636"
                    text-header: "#ffffff"
                    text-title: "#303030"
                    text-subtitle: "#424242"
                    card-shadow: rgba(0, 0, 0, 0.1)
                    link: "#3273dc"
                    link-hover: "#363636"
                  dark:
                    highlight-primary: "#3367d6"
                    highlight-secondary: "#4285f4"
                    highlight-hover: "#5a95f5"
                    background: "#131313"
                    card-background: "#2b2b2b"
                    text: "#eaeaea"
                    text-header: "#ffffff"
                    text-title: "#fafafa"
                    text-subtitle: "#f5f5f5"
                    card-shadow: rgba(0, 0, 0, 0.4)
                    link: "#3273dc"
                    link-hover: "#ffdd57"
                
                services:
                  - name: "Monitoring & Observability"
                    icon: "fas fa-chart-line"
                    items:
                      - name: "Grafana"
                        logo: "https://grafana.com/static/img/menu/grafana2.svg"
                        subtitle: "Metrics, Logs & Traces Visualization"
                        tag: "LGTM"
                        url: "https://grafana.milenika.dev/d/homelab-overview/homelab-overview-lgtm-stack"
                        target: "_blank"
                      - name: "Prometheus"
                        logo: "https://raw.githubusercontent.com/prometheus/prometheus/main/documentation/images/prometheus-logo.svg"
                        subtitle: "Metrics Collection & Alerting"
                        tag: "metrics"
                      - name: "Loki"
                        logo: "https://grafana.com/static/img/logos/logo-loki.svg"
                        subtitle: "Log Aggregation"
                        tag: "logs"
                      - name: "Tempo"
                        logo: "https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png"
                        subtitle: "Distributed Tracing"
                        tag: "traces"
                  
                  - name: "Infrastructure"
                    icon: "fas fa-server"
                    items:
                      - name: "ArgoCD"
                        logo: "https://argo-cd.readthedocs.io/en/stable/assets/logo.png"
                        subtitle: "GitOps Continuous Delivery"
                        tag: "gitops"
                        url: "https://argocd.milenika.dev"
                        target: "_blank"
                      - name: "Homer Dashboard"
                        logo: "https://github.com/bastienwirtz/homer/raw/main/public/logo.png"
                        subtitle: "This Homepage"
                        tag: "dashboard"
                        url: "https://homer.milenika.dev"
                        target: "_blank"
                  
                  - name: "Source Code"
                    icon: "fab fa-github"
                    items:
                      - name: "GitOps Repository"
                        logo: "https://github.com/fluidicon.png"
                        subtitle: "Homelab GitOps configurations"
                        tag: "kubernetes"
                        url: "https://github.com/mikha-22/homelab-gitops"
                        target: "_blank"
                      - name: "IaC Repository"
                        logo: "https://github.com/fluidicon.png"
                        subtitle: "Terraform & Automation"
                        tag: "terraform"
                        url: "https://github.com/mikha-22/homelab-iac"
                        target: "_blank"
                
                message:
                  style: "is-dark"
                  title: "Welcome to Mikha's Homelab!"
                  icon: "fa fa-grin"
                  content: "This dashboard provides quick access to all your homelab services. Your LGTM observability stack is fully operational with Loki (logs), Grafana (visualization), Tempo (traces), and Prometheus (metrics)."
    
  destination:
    server: https://kubernetes.default.svc
    namespace: homer
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
