# apps/system/homer-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    # Source 1: The Helm chart from the remote repository
    - repoURL: https://djjudas21.github.io/charts/
      targetRevision: 8.2.4
      chart: homer
      helm:
        releaseName: homer
        valueFiles:
          - $values/apps/homer/values.yaml

    # Source 2: Your Git repository, providing the values file
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      ref: values
      
  destination:
    server: https://kubernetes.default.svc
    namespace: homer
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
