# apps/system/kustomization.yaml
resources:
  # Projects (must be first)
  - projects/monitoring-project.yaml
  
  # Infrastructure (-1 to 0 sync waves)
  - external-secrets-app.yaml    # wave: -1
  
  # Monitoring Stack (0 to 5 sync waves)
  - monitoring-namespace-app.yaml # wave: 0
  - prometheus-app.yaml          # wave: 1
  - loki-app.yaml               # wave: 2
  - tempo-app.yaml              # wave: 3
  - otel-collector-app.yaml     # wave: 4 
  - dashboards-app.yaml         # wave: 5
  
  # Demo Applications
  - opentelemetry-demo-app.yaml  # wave: 20
  
  # Applications (10+ sync waves)
  - homer-app.yaml              # wave: 10
  - minio-app.yaml              # wave: 10
  - nginx-app.yaml              # wave: 15
