# apps/system/kustomization.yaml - ADD ONE LINE AT THE END
resources:
  # Projects (must be first)
  - projects/monitoring-project.yaml
  
  # Infrastructure (-2 to 0 sync waves)
  - shared-config-app.yaml       # wave: -2
  - external-secrets-app.yaml    # wave: -1
  
  # Monitoring Stack (0 to 5 sync waves)
  - monitoring-namespace-app.yaml # wave: 0
  - prometheus-app.yaml          # wave: 1
  - loki-app.yaml               # wave: 2
  - tempo-app.yaml              # wave: 3
  - otel-app.yaml               # wave: 3
  - promtail-app.yaml           # wave: 4
  - dashboards-app.yaml         # wave: 5
  - opentelemetry-demo-app.yaml           # ADD THIS LINE
  
  # Applications (10+ sync waves)
  - homer-app.yaml              # wave: 10
  - minio-app.yaml              # wave: 10
  - nginx-app.yaml              # wave: 15
