apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/monitoring-project.yaml
  - monitoring-namespace-app.yaml
  - prometheus-app.yaml
  - loki-app.yaml          # UNCOMMENTED FOR LOKI
#   - tempo-app.yaml         # KEEP COMMENTED FOR NOW
  - promtail-app.yaml
  
# Common labels for all system applications
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: homelab-gitops
      environment: homelab
