# apps/system/loki-app.yaml - FINAL CORRECTED FILE

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: monitoring
  sources:
    # Source 1: The official Loki Helm chart
    - repoURL: https://grafana.github.io/helm-charts
      # THIS IS THE KEY: Use the correct chart version
      targetRevision: 6.30.1
      chart: loki
      helm:
        releaseName: loki
        # This tells ArgoCD to get values from the source named 'values'
        valueFiles:
          - $values/apps/monitoring/loki-values.yaml

    # Source 2: Your Git repository, providing the local values file
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      # This 'ref' creates a named source called 'values' that ArgoCD can reference
      ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace:true
      - ServerSideApply=true
