# apps/system/online-boutique-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"  # Deploy after all infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/GoogleCloudPlatform/microservices-demo
    targetRevision: v0.10.1
    path: kubernetes-manifests
    # Remove kustomize section and use plain manifests
    
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
