apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"  # Deploy after all infrastructure
spec:
  project: default
  sources:
    # Source 1: OpenTelemetry Demo Helm chart
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.32.6  # Latest stable version
      chart: opentelemetry-demo
      helm:
        releaseName: otel-demo
        valueFiles:
          - $values/apps/opentelemetry-demo/values.yaml
    # Source 2: Your Git repository with values
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  # Ignore replica differences during autoscaling
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
