# system/otel-collector-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Deploy this in sync-wave 4, replacing Promtail.
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: monitoring
  sources:
    # Source 1: The official OpenTelemetry Collector Helm chart.
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.131.0 # Use a specific, recent version
      chart: opentelemetry-collector
      helm:
        releaseName: otel-collector
        valueFiles:
          # This tells Helm to get its values from our new file.
          - $values/monitoring/otel-collector-values.yaml

    # Source 2: Your Git repository, providing the values file.
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # The monitoring namespace is created in wave 0, so we don't need to create it here.
      - CreateNamespace=false
      - ServerSideApply=true
