# apps/system/otel-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # After Tempo (wave 3), before applications
spec:
  project: monitoring
  sources:
    # Source 1: OpenTelemetry Helm chart
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.129.0
      chart: opentelemetry-collector
      helm:
        releaseName: otel-collector
        valueFiles:
          - $values/apps/otel/values.yaml
    # Source 2: Git repository with values
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # monitoring namespace already exists
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  # Ignore replica differences during autoscaling
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
