apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: monitoring
  sources:
    # Source 1: The Helm chart from the remote repository
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.23.2
      chart: tempo
      helm:
        releaseName: tempo
        valueFiles:
          # This now references the 'values' source below
          - $values/apps/monitoring/tempo-values.yaml

    # Source 2: Your Git repository, providing the values file
    - repoURL: https://github.com/mikha-22/homelab-gitops
      targetRevision: HEAD
      # This 'ref' is a special key ArgoCD uses to identify this source
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  # ADD THIS: Ignore differences in StatefulSet volumeClaimTemplates
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
        - /spec/volumeClaimTemplates/0/status
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.volumeClaimTemplates[]?.metadata.creationTimestamp'
        - '.spec.volumeClaimTemplates[]?.status'
