apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
