# apps/external-secrets/grafana-external-secret.yaml - FIXED
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-admin-secret
    app.kubernetes.io/part-of: homelab-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: grafana-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
