apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-secret
    app.kubernetes.io/part-of: homelab-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootUser: "{{ .rootUser }}"
        rootPassword: "{{ .rootPassword }}"
        hugo-secret-key: "{{ .hugoSecretKey }}"
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-root-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: rootPassword
      remoteRef:
        key: minio-root-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: hugoSecretKey
      remoteRef:
        key: minio-hugo-secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
