# apps/external-secrets/test-cname-external-secret.yaml
# TEST: Can ESO fetch the tunnel CNAME?

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-tunnel-cname
  namespace: kube-system  # Put it where we need it
  labels:
    app.kubernetes.io/name: test-tunnel-cname
    app.kubernetes.io/part-of: homelab-gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: tunnel-cname-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cname: "{{ .tunnelCname }}"
  data:
    - secretKey: tunnelCname
      remoteRef:
        key: tunnel-cname  # This should match what Terraform created
