# Add this section to your existing loki-values.yaml

# Enable official Loki dashboards
monitoring:
  dashboards:
    enabled: true
    labels:
      grafana_dashboard: "1"
    annotations:
      grafana_folder: "Loki"
  
  # ServiceMonitor is already enabled in your config, this is just for reference
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack
    interval: 30s
    annotations: {}

# If you want the full monitoring suite
lokiCanary:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

# Self-monitoring (optional - can be heavy for homelab)
monitoring:
  dashboards:
    enabled: true
    labels:
      grafana_dashboard: "1"
  selfMonitoring:
    enabled: false  # Keep this disabled for homelab
    grafanaAgent:
      installOperator: false
