# FILE: apps/monitoring/loki-values.yaml
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  storage:
    type: filesystem
    filesystem:
      directory: /data/loki
  
  # Set a reasonable retention period for logs
  limits_config:
    retention_period: 7d

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 20Gi
