# apps/monitoring/tempo-values.yaml (FINAL FIX)

replicas: 1

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

serviceMonitor:
  enabled: true

metricsGenerator:
  enabled: true
  remoteWriteUrl: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  # ADDED: Explicit ring configuration to solve the "empty ring" error.
  # This allows the generator to register itself so the querier can find it.
  ring:
    kvstore:
      store: memberlist

tempo:
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 8Gi

  multitenancyEnabled: false
  reportingEnabled: false
  retention: 168h
  memBallastSizeMbs: 2048
  
  server:
    http_listen_port: 3200
  
  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
