# apps/monitoring/tempo-values.yaml

# Global configuration
global:
  image:
    tag: "2.8.0"

# Tempo configuration
tempo:
  repository: grafana/tempo
  pullPolicy: IfNotPresent
  
  # Resource management
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  # CORRECTED: The entire tempo.yaml configuration is now a single block string.
  # This matches the expectation of chart version 1.23.2.
  config: |
    multitenancy_enabled: false

    server:
      http_listen_port: 3200
      log_level: info

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317

    ingester:
      max_block_duration: 5m

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    # This enables TraceQL search
    querier:
      search_enabled: true

    # This enables the metrics generator with the CORRECT remote write URL
    metrics_generator:
      storage:
        path: /var/tempo/generator-wal
        remote_write:
          - url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
            send_exemplars: true

# Persistence configuration
persistence:
  enabled: true
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# Service configuration (ports remain the same)
service:
  type: ClusterIP
  ports:
    - name: tempo-prom-metrics
      port: 3200
      targetPort: 3200
    - name: tempo-otlp-http
      port: 4318
      targetPort: 4318
    - name: tempo-otlp-grpc
      port: 4317
      targetPort: 4317
# ... (you can add other ports like jaeger back if you need them)

# ServiceMonitor for Prometheus integration
serviceMonitor:
  enabled: true
  interval: 30s
