# apps/monitoring/tempo-values.yaml
# This configuration is compatible with tempo chart version 1.23.2

# This block controls the Kubernetes resources
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

persistence:
  enabled: true
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 10Gi

serviceMonitor:
  enabled: true
  interval: 30s

# This block passes configuration values to Tempo
tempo:
  retention: 168h # Set retention to 7 days
  
  # This enables the metrics generator and provides the CORRECT remote write URL
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"

  # This enables TraceQL search
  querier:
    search_enabled: true
