# apps/monitoring/tempo-values.yaml
# MINIMAL WORKING CONFIGURATION - Based on chart defaults

# Basic deployment
replicas: 1

# Resources for homelab
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

# Persistence
persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

# Enable ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true

# Tempo configuration using chart structure
tempo:
  # Basic settings
  multitenancyEnabled: false
  reportingEnabled: false
  retention: 168h  # 7 days
  
  # Enable metrics generator with proper remote write
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
