# apps/monitoring/tempo-values.yaml - Conservative retention settings

replicas: 1

persistence:
  enabled: true
  storageClassName: local-path
  # REDUCED: From 10Gi to 7Gi (conservative)
  size: 7Gi

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-stack

# Use the chart's built-in metrics generator support
tempo:
  ingester:
    trace_idle_period: 60s
    flush_check_period: 60s
    # REDUCED: From 15m to 10m (conservative)
    max_block_duration: 10m
  # Enable metrics generator - THIS IS THE KEY!
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"

  # Server configuration
  server:
    http_listen_port: 3200

  # Resource configuration
  resources:
    requests:
      cpu: 500m
      # REDUCED: From 4Gi to 3Gi (conservative)
      memory: 3Gi
    limits:
      cpu: 1000m
      # REDUCED: From 8Gi to 5Gi (conservative)
      memory: 5Gi

  # Other Tempo settings
  multitenancyEnabled: false
  reportingEnabled: false
  # REDUCED: From 168h (7 days) to 48h (2 days) - conservative
  retention: 48h
  # REDUCED: From 2048 to 1536 (conservative)
  memBallastSizeMbs: 1536

  # Storage configuration (keep the defaults working)
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  # CRITICAL: Enable metrics generation with ALL required processors
  overrides:
    defaults:
      metrics_generator:
        processors: 
          - "span-metrics"
          - "service-graphs"
          - "local-blocks"  # ADD THIS - Required for TraceQL metrics drilldown

  # Health check configuration
  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
