# apps/monitoring/tempo-values.yaml (DEFINITIVE FIX)

replicas: 1

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

serviceMonitor:
  enabled: true

# All runtime settings are now correctly nested inside this 'tempo:' block.
tempo:
  # This is the full runtime configuration for the metrics generator.
  metrics_generator:
    ring:
      kvstore:
        store: memberlist
    storage:
      remote_write:
        - url: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"

  # This part is also correct and activates the generator's processor.
  overrides:
    defaults:
      metrics_generator:
        processors:
        - span-metrics

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 8Gi

  multitenancyEnabled: false
  reportingEnabled: false
  retention: 168h
  memBallastSizeMbs: 2048
  
  server:
    http_listen_port: 3200
  
  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
