apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/mikha-22/homelab-gitops # Your repo URL
    targetRevision: HEAD
    path: charts/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring # Deploy all resources into this namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
