# apps/opentelemetry-demo/values.yaml

# 1. Disable bundled observability tools we already have.
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

# 2. Disable the demo's built-in collector.
opentelemetry-collector:
  enabled: false

# 3. Configure components.
components:
  frontend:
    # We ONLY need to provide the HOST_IP variable for the patch's script to use.
    # The command, args, and OTEL_EXPORTER_OTLP_ENDPOINT are now handled by the patch.
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  frontend-proxy:
    # This component and all others still need the direct override, as the
    # patch only targets the 'frontend' deployment.
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "e0995bb5-0641-44ba-9ac6-533e678117a2.cfargotunnel.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "monitoring-security-headers@kubernetescrd"
      hosts:
        - host: "otel-demo.milenika.dev"
          paths:
            - path: /
              pathType: Prefix
              port: 8080
      tls:
        - secretName: otel-demo-tls
          hosts:
            - "otel-demo.milenika.dev"

  ad:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "300Mi", cpu: "200m" }
      requests: { memory: "180Mi", cpu: "100m" }

  cart:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "160Mi", cpu: "100m" }

  checkout:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  currency:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  email:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  payment:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  product-catalog:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  recommendation:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "500Mi", cpu: "200m" }
      requests: { memory: "200Mi", cpu: "100m" }

  shipping:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  load-generator:
    # This component has its own specific variables
    env:
      - name: LOCUST_USERS
        value: "5"
      - name: LOCUST_SPAWN_RATE
        value: "1"
    # And it also needs our OTLP override
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
