# apps/opentelemetry-demo/values.yaml - All components enabled, with per-component overrides

# 1. Disable bundled observability tools
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

# 2. Disable the demo's built-in collector
opentelemetry-collector:
  enabled: false

# 3. Global configuration - Set variables that are MISSING from the chart defaults.
default:
  envOverrides:
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_SDK_DEBUG
      value: "true"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"

# 4. Configure all components, ensuring each has the correct endpoint override.
components:
  frontend:
    envOverrides:
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  frontend-proxy:
    envOverrides:
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "e0995bb5-0641-44ba-9ac6-533e678117a2.cfargotunnel.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "monitoring-security-headers@kubernetescrd"
      hosts:
        - host: "otel-demo.milenika.dev"
          paths:
            - path: /
              pathType: Prefix
              port: 8080
      tls:
        - secretName: otel-demo-tls
          hosts:
            - "otel-demo.milenika.dev"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  ad:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "300Mi", cpu: "200m" }
      requests: { memory: "180Mi", cpu: "100m" }

  cart:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "160Mi", cpu: "100m" }

  checkout:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  currency:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  email:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  payment:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  product-catalog:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  recommendation:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "500Mi", cpu: "200m" }
      requests: { memory: "200Mi", cpu: "100m" }

  shipping:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }
      
  # Add configurations for the default components you are keeping enabled
  fraud-detection:
    enabled: true # This is the default, but we make it explicit
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "300Mi", cpu: "200m" }
      requests: { memory: "150Mi", cpu: "100m" }

  accounting:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  quote:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  image-provider:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "100Mi", cpu: "100m" }
      requests: { memory: "50Mi", cpu: "50m" }

  valkey-cart: # This is the new name for the redis-cart service
    enabled: true
    # This component is not instrumented, so no OTel variables needed
    resources:
      limits: { memory: "100Mi", cpu: "100m" }
      requests: { memory: "50Mi", cpu: "50m" }

  kafka:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "600Mi", cpu: "500m" }
      requests: { memory: "300Mi", cpu: "200m" }

  load-generator:
    env:
      - name: LOCUST_USERS
        value: "5"
      - name: LOCUST_SPAWN_RATE
        value: "1"
      - name: LOCUST_LOGLEVEL
        value: "INFO"
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }
