# apps/opentelemetry-demo/values.yaml - WORKING VERSION

# 1. Disable bundled observability tools
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

# 2. Disable the demo's built-in collector
opentelemetry-collector:
  enabled: false

# 3. Configure components with working HOST_IP expansion
components:
  frontend:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      # Use a shell wrapper to expand the variable
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    # Override the container command to use shell expansion
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec node server.js"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  frontend-proxy:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec /usr/local/bin/envoy -c /etc/envoy/envoy.yaml"]
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "e0995bb5-0641-44ba-9ac6-533e678117a2.cfargotunnel.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "monitoring-security-headers@kubernetescrd"
      hosts:
        - host: "otel-demo.milenika.dev"
          paths:
            - path: /
              pathType: Prefix
              port: 8080
      tls:
        - secretName: otel-demo-tls
          hosts:
            - "otel-demo.milenika.dev"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  ad:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec java -jar /app/Ad.jar"]
    resources:
      limits: { memory: "300Mi", cpu: "200m" }
      requests: { memory: "180Mi", cpu: "100m" }

  cart:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec dotnet Cart.dll"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "160Mi", cpu: "100m" }

  checkout:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec go run main.go"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  currency:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec node server.js"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  email:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec ruby email_server.rb"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  payment:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec node index.js"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  product-catalog:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec go run main.go"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  recommendation:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec python recommendation_server.py"]
    resources:
      limits: { memory: "500Mi", cpu: "200m" }
      requests: { memory: "200Mi", cpu: "100m" }

  shipping:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec rust-executable"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  load-generator:
    env:
      - name: LOCUST_USERS
        value: "5"
      - name: LOCUST_SPAWN_RATE
        value: "1"
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "$(HOST_IP):4317"
    command: ["/bin/sh", "-c"]
    args: ["export OTEL_EXPORTER_OTLP_ENDPOINT=\"$HOST_IP:4317\" && exec locust --host http://frontend:8080"]
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }
