# apps/opentelemetry-demo/values.yaml - Centralized OTel Configuration

# 1. Disable bundled observability tools
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

# 2. Disable the demo's built-in collector
opentelemetry-collector:
  enabled: false

# 3. Global configuration - Centralized OTel settings for all services
default:
  envOverrides:
    # Common debug settings
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_SDK_DEBUG
      value: "true"
      
    # Global exporter settings for all services to use
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"

# 4. Configure components - Redundant OTel env vars removed
components:
  frontend:
    envOverrides:
      # Sampler is specific to this component, so it stays
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  frontend-proxy:
    envOverrides:
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "e0995bb5-0641-44ba-9ac6-533e678117a2.cfargotunnel.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "monitoring-security-headers@kubernetescrd"
      hosts:
        - host: "otel-demo.milenika.dev"
          paths:
            - path: /
              pathType: Prefix
              port: 8080
      tls:
        - secretName: otel-demo-tls
          hosts:
            - "otel-demo.milenika.dev"
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  ad:
    # No specific envOverrides needed, will inherit from default
    resources:
      limits: { memory: "300Mi", cpu: "200m" }
      requests: { memory: "180Mi", cpu: "100m" }

  cart:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "160Mi", cpu: "100m" }

  checkout:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  currency:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  email:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  payment:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  product-catalog:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  recommendation:
    resources:
      limits: { memory: "500Mi", cpu: "200m" }
      requests: { memory: "200Mi", cpu: "100m" }

  shipping:
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }

  load-generator:
    env:
      - name: LOCUST_USERS
        value: "5"
      - name: LOCUST_SPAWN_RATE
        value: "1"
      - name: LOCUST_LOGLEVEL
        value: "INFO"
    # envOverrides are no longer needed here as they are covered by the 'default' section
    resources:
      limits: { memory: "200Mi", cpu: "200m" }
      requests: { memory: "100Mi", cpu: "100m" }
