# This is a simple configuration for a daemonset collector
mode: daemonset

# Main config for the collector's behavior
config:
  receivers:
    otlp:
      protocols:
        # This opens the port to listen for OTLP trace data from apps
        grpc:
        http:

  processors:
    batch:

  exporters:
    otlp:
      # This forwards the traces it receives to your existing Tempo service
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
