# NGINX Configuration for Hugo Static Site Hosting via MinIO
# Based on Bitnami NGINX Helm Chart v21.0.6 (Latest)
# SIMPLE FIX: Just handle root path properly

## Global Docker image parameters
image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.27.3-debian-12-r1 # Latest stable NGINX 1.27.3
  pullPolicy: IfNotPresent
  pullSecrets: []

## Force target Kubernetes version (to silence chart warnings)
kubeVersion: ""

## String to partially override nginx.fullname
nameOverride: ""
fullnameOverride: ""

## Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
hostAliases: []

## Number of nginx replicas to deploy
replicaCount: 2

## Update strategy
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

## Pod Management Policy
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
podManagementPolicy: Parallel

## Pod Disruption Budget configuration
pdb:
  create: true
  minAvailable: 1

## Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPU: 70
  targetMemory: 80

## Custom server block for proxying to MinIO - SIMPLE ROOT PATH FIX
serverBlock: |-
  # Upstream for MinIO S3 API
  upstream minio_s3 {
      server minio.minio.svc.cluster.local:9000;
      keepalive 32;
  }

  server {
      listen 8080;
      server_name _;
      access_log /dev/stdout; # <-- ADD THIS LINE

      # Security headers
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;

      # Gzip compression for better performance
      gzip on;
      gzip_vary on;
      gzip_min_length 1024;
      gzip_types
          text/plain
          text/css
          text/xml
          text/javascript
          application/javascript
          application/json
          application/xml+rss
          application/atom+xml
          image/svg+xml;

      # SIMPLEST FIX: Just rewrite root to index.html
      location / {
          # Rewrite root path to index.html
          rewrite ^/$ /index.html last;

          # Serve all files from MinIO
          proxy_pass http://minio_s3/hugo-static$uri;

          # Proxy headers
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          # HTTP/1.1 for keepalive
          proxy_http_version 1.1;
          proxy_set_header Connection "";

          # Timeouts
          proxy_connect_timeout 10s;
          proxy_send_timeout 30s;
          proxy_read_timeout 30s;

          # Cache static assets
          location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
              proxy_pass http://minio_s3/hugo-static$uri;

              # Cache headers
              expires 30d;
              add_header Cache-Control "public, no-transform, immutable";
              add_header Vary "Accept-Encoding";

              # Same proxy headers
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_http_version 1.1;
              proxy_set_header Connection "";
          }

          # Special handling for HTML files
          location ~* \.html$ {
              proxy_pass http://minio_s3/hugo-static$uri;

              # No caching for HTML files
              expires -1;
              add_header Cache-Control "no-cache, no-store, must-revalidate";
              add_header Pragma "no-cache";

              # Same proxy headers
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_http_version 1.1;
              proxy_set_
