apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-conf
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  url: "https://argocd.milenika.dev"
