# apps/online-boutique/kustomization.yaml - REMOVE LOADBALANCER
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: homelab-gitops
      environment: homelab
      component: microservices-demo
      
commonAnnotations:
  deployed-by: argocd

# Set the namespace for all resources
namespace: online-boutique

# Remove the problematic LoadBalancer service entirely
patches:
- target:
    kind: Service
    name: frontend-external
  patch: |-
    $patch: delete
