# apps/online-boutique/kustomization.yaml - SIMPLE & WORKING
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: homelab-gitops
      environment: homelab
      component: microservices-demo
      
commonAnnotations:
  deployed-by: argocd

# Set the namespace for all resources
namespace: online-boutique
