apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab # <-- ADD THIS LINE. This is the fix.
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.8.0
    helm:
      values: |
        # Ingress settings for Grafana
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - "grafana.milenika.dev"
            annotations:
              # These annotations are critical for your Cloudflare Tunnel setup
              external-dns.alpha.kubernetes.io/target: "e36ab9bf-8074-4886-ad3a-5b1cf5dce20a.cfargotunnel.com"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

        # Ingress settings for Prometheus
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - "prometheus.milenika.dev"
            annotations:
              external-dns.alpha.kubernetes.io/target: "e36ab9bf-8074-4886-ad3a-5b1cf5dce20a.cfargotunnel.com"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
