apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1 # Using the correct, up-to-date chart version
    helm:
      values: |
        # This is the modern way to enable the full stack.
        # We are enabling the promtail sub-chart from within the loki chart.
        promtail:
          enabled: true

        loki:
          # Disabling authentication for a simple homelab setup.
          auth_enabled: false
        
        # Configure Ingress for the Loki service.
        # Note the path to the ingress config is slightly different in this chart.
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: loki.milenika.dev
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            # Your critical annotations for the Cloudflare Tunnel
            external-dns.alpha.kubernetes.io/target: "e36ab9bf-8074-4886-ad3a-5b1cf5dce20a.cfargotunnel.com"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
