# apps/monitoring/namespace/loki-servicemonitor.yaml - FIXED

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/part-of: homelab-gitops
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      # REMOVED: app.kubernetes.io/component: single-binary  # This label doesn't exist on the service
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - monitoring
