apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: homelab-gitops
    # RELAX security for monitoring components that need privileges
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged  
    pod-security.kubernetes.io/warn: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
# Add resource quota for better resource management
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-quota
    app.kubernetes.io/part-of: homelab-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    requests.storage: 100Gi
---
# Add limit range for default resource limits - FIXED for Tempo
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-limits
    app.kubernetes.io/part-of: homelab-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:  # ADDED: Allow higher limits for resource-heavy containers like Tempo
      cpu: 2000m
      memory: 8Gi
    type: Container
