apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-demo-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: otel-demo-collector
    app.kubernetes.io/part-of: homelab-gitops
    release: prometheus-stack  # This makes Prometheus discover it
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/instance: otel-demo
      component: standalone-collector
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - otel-demo  # Monitor services in the otel-demo namespace
