apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    # Generator 1: Manages cluster-wide configurations (e.g., Namespaces)
    - git:
        repoURL: https://github.com/mikha-22/homelab-gitops
        revision: HEAD
        directories:
          - path: cluster/overlays/*
      # The template for the cluster generator
      template:
        metadata:
          name: 'cluster-{{path.basename}}'
        spec:
          project: default
          source:
            repoURL: https://github.com/mikha-22/homelab-gitops
            targetRevision: HEAD
            path: '{{path}}'
            kustomize: {} # Use kustomize to read the directory
          destination:
            server: https://kubernetes.default.svc
            namespace: '{{path.basename}}'
          syncPolicy:
            automated: {prune: true, selfHeal: true}
            syncOptions: [CreateNamespace=true]

    # Generator 2: Manages all deployable applications
    - git:
        repoURL: https://github.com/mikha-22/homelab-gitops
        revision: HEAD
        directories:
          - path: apps/*
          - exclude: true
            path: apps/argocd # This prevents a recursive loop!
      # The template for the applications generator
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          project: '{{path.basename}}' # Dynamically assign project based on folder name
          source:
            repoURL: https://github.com/mikha-22/homelab-gitops
            targetRevision: HEAD
            path: '{{path}}/homelab' # Crucial: Points to the Kustomize overlay
            kustomize: {} # Use kustomize to read the directory
          destination:
            server: https://kubernetes.default.svc
            namespace: '{{path.basename}}'
          syncPolicy:
            automated: {prune: true, selfHeal: true}
            syncOptions: [CreateNamespace=true]
