# FILE: apps/argocd/applications-appset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mikha-22/homelab-gitops
        revision: HEAD
        directories:
          - path: apps/*
          - exclude: true
            path: apps/argocd # Exclude this directory to prevent recursion
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: '{{path.basename}}'
      source:
        repoURL: https://github.com/mikha-22/homelab-gitops
        targetRevision: HEAD
        path: '{{path}}/homelab' # This resolves to 'apps/monitoring/homelab'
        
        # THIS IS THE CRITICAL FIX
        # This tells Argo CD to run 'kustomize build --enable-helm'
        # for the 'monitoring' application.
        kustomize:
          helmEnabled: true
          
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {prune: true, selfHeal: true}
        syncOptions: [CreateNamespace=true]
