apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mikha-22/homelab-gitops
        revision: HEAD
        directories:
          - path: cluster/overlays/*
  template:
    metadata:
      name: '{{path.basename}}-cluster-setup'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mikha-22/homelab-gitops
        targetRevision: HEAD
        path: '{{path}}'
        kustomize: {} # Process the kustomization.yaml in the target directory
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {prune: true, selfHeal: true}
        syncOptions: [CreateNamespace=true]
