apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy before monitoring
spec:
  generators:
    - git:
        repoURL: https://github.com/mikha-22/homelab-gitops
        revision: HEAD
        directories:
          - path: cluster/overlays/*
  template:
    metadata:
      name: '{{path.basename}}-cluster-setup'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: https://github.com/mikha-22/homelab-gitops
        targetRevision: HEAD
        path: '{{path}}'
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions: 
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
